#!/bin/bash
set -eou pipefail

. scripts/common.sh

validate_compile () {
	echo "compiling..." >&2

	npm run compile
}

validate_compile () {
	echo "compiling..." >&2
	
	npm run build
}

validate_circleci_config () {
	echo "validating CircleCI config..." >&2

	if ! git diff --name-only --staged | grep -q 'circleci/config.yml'; then
		echo "circleci/config.yml is not staged for commit, skipping validation..." >&2
		return 0
	fi

	echo "validing CircleCI config..." >&2
	if command -v circleci; then
		circleci config validate
	else
		wsl circleci config validate
	fi
}

########## MAIN BLOCK ##########
validate_compile
validate_circleci_config
validate_version_updated
echo "pre-commit checks successful!" >&2
