using OpenEdge.Core.Assert.

class testNames2:

    @Test.
    method public void Test_testNameTest ():
    end method.

    @Test.
    method public void Test_testName# ():
    end method.

    @Test.
    method public void Test_testName#_goodValue ():
    end method.

    @Test.
    method public void Test_testName#_newValue ():
    end method.

    @Test.
    method public void Test_testName_newValue ():
    end method.

    @Test.
    method public void Test_noHashtag ():
    end method.

end class.
