name: "🐛 Bug Report"
description: File a bug report
title: "🐛 [Bug]  <title here>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**  Your contribution helps this extension continue to be useful for the OpenEdge community.  Issues are triaged on a regular basis, but please be patient as we work through the backlog.  Pull requests are always welcome if you'd like to tackle the issue yourself.
  - type: dropdown
    id: extversion
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      options:
        - 1.1.3
        - 1.1.1
        - 1.1.0
        - 1.0.0
        - other (please specify in the description)
  - type: dropdown
    id: oeversion
    attributes:
      label: OpenEdge Version
      description: What version of our software are you running?
      options:
        - '12.8'
        - '12.2'
        - '12.0'
        - '11.7'
        - '11.6'
        - '11.X'
        - '10.X'
        - '9.X'
        - 'other (please specify in the description)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Chore Description
      value: |
        Describe the chore...
    validations:
      required: true
