name: ":bug: Bug Report"
description: File a bug report
title: ":bug: [bug] <title here please>"
labels: ["bug", "triage"]
# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - octocat
body:
  - type: dropdown
    id: version
    attributes:
      label: OpenEdge Version
      description: What version of our software are you running?
      options:
        - 12.8
        - 12.2
        - 12.0
        - 11.7
        - 11.6
        - 11.X
        - 10.X
        - 9.X
        - other (please specify in the description)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
    validations:
      required: true
