name: Question
description: Ask a question
title: "🙋‍♀️ [Question] "
labels: ["question"]
# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        Ask your question and provide as much context as possible...
