name: "Question"
description: Ask a question
title: "🙋‍♀️ [Question] <title here>"
labels: ["question"]
# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - octocat
body:
  - type: dropdown
    id: version
    attributes:
      label: OpenEdge Version
      description: What version of our software are you running?
      options:
        - 12.8
        - 12.2
        - 12.0
        - 11.7
        - 11.6
        - 11.X
        - 10.X
        - 9.X
        - other (please specify in the description)
  - type: markdown
    attributes:
      value: |
        Ask your question and provide as much context as possible...
    validations:
      required: true
