name: "🙋‍♀️ Question"
description: Ask a question
title: "🙋‍♀️ [Question] <title here>"
labels: ["question"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - kherring
body:
  - type: markdown
    attributes:
      value: |
        Ask a question, and please be sure to provide as much context as is necessary.
  - type: dropdown
    id: extversion
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      options:
        - 1.1.7
        - 1.1.0
        - 1.0.0
        - other (please specify in the description)
  - type: dropdown
    id: version
    attributes:
      label: OpenEdge Version
      description: What version of our software are you running?
      options:
        - '12.8'
        - '12.2'
        - '12.0'
        - '11.7'
        - '11.6'
        - '11.X'
        - '10.X'
        - '9.X'
        - 'other (please specify in the description)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Question
      value: |
        Ask your question here...
    validations:
      required: true
