block-level on error undo, throw.
using OpenEdge.Core.Assert.

class template_class :

	@Test.
	method public void testMethod0 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod1 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod2 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod3 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod4 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod5 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod6 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod7 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod8 () :
	  Assert:Equals(1,1).
	end method.

	@Test.
	method public void testMethod9 () :
	  Assert:Equals(1,1).
	end method.

end class.
