name: Fork Approval

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  trigger-main-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main workflow
        uses: .github/workflows/main.yml
