name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: validate user
        # if: ${{ github.event_name == "pull_request_target" }}
        run: |
          echo "github.actor=${{ github.actor }}"
          if [ "${{ github.actor }}" != "kenherring" ] && [ "${{ github.actor }}" != "dependabot[bot]" ]; then
            echo "Unauthorized user. Stopping workflow run..."
            exit 1
          fi
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request_target' && github.head_ref || github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          token: ${{ secrets.MY_GITHUB_TOKEN || github.token }}
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: ./test_projects/**
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: ./scripts/package.sh
      - run: ./scripts/bump_version.sh
        # continue-on-error: true
        if: ${{ github.head_ref != 'main' }}
        env:
          GH_TOKEN: ${{ github.token }}

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        oe-version: [ 12.2.19, 12.8.1, 12.8.11 ]
    runs-on: ubuntu-latest
    container:
      image: kherring/ablunit-test-runner:${{ matrix.oe-version }}
      credentials:
        username: ${{ secrets.DOCKER_USER || 'undefined' }}
        password: ${{ secrets.DOCKER_PAT || 'undefined' }}
    env:
      ABLUNIT_TEST_RUNNER_OE_VERSION: ${{ matrix.oe-version }}
      ABLUNIT_TEST_RUNNER_VSCODE_VERSION: 'stable'
      EXPECTED_VSIX_COUNT: 1
      GH_TOKEN: ${{ github.token }}
      PRIMARY_OE_VERSION: 12.8.1
      PROGRESS_CFG_BASE64: ${{ secrets.PROGRESS_CFG_BASE64 }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: ./scripts/run_test_wrapper.sh
      - run: ./scripts/sonar_test_results_merge.sh
      - name: SonarQube Scan - main
        if: ${{ matrix.oe-version == '12.8.1' && github.actor != 'dependabot[bot]' && github.head_ref == 'main' }}
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarQube Scan
        if: ${{ matrix.oe-version == '12.8.1' && github.actor != 'dependabot[bot]' && github.head_ref != 'main' }}
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      - uses: actions/upload-artifact@v7
        if: ${{ matrix.oe-version == '12.8.1' }}
        with:
          name: package-artifact
          path: ./ablunit-test-runner*.vsix

  create-release:
    needs: [ 'test' ]
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'main' && github.event_name != 'pull_request_target' && github.event_name == 'pull_request'}}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v8
        with:
          name: package-artifact
      - name: create release
        run: ./scripts/create_release.sh
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
